name: Android Development Build

on:
  push:
    branches: ['main', 'develop']

jobs:
  build_android_dev:
    name: Build Android Development APK
    type: build
    params:
      platform: android
      profile: development
